// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: { 
    // DIRECT_URL = session-mode pooler; migrations need a direct connection (pgbouncer can't run DDL).
    url: process.env["DIRECT_URL"],
  },
});
